### PR TITLE
feat: Module

### PR DESCRIPTION
**Pull request by SudhanPlayz**

### CODE REVIEW

**Comment by SudhanPlayz** [comment]
@DarrenOfficial Check and merge

**Comment by DarrenOfficial** [comment]
Such big commit

**Comment by SudhanPlayz** [comment]
Merge it as soon as possible

**Comment by DarrenOfficial** [comment]
I can't

**Comment by DarrenOfficial** [comment]
Because bugs and issue

**Comment by DarrenOfficial** [comment]
Plus I haven't even gotten it to work both on my pc and server

**Comment by SudhanPlayz** [comment]
But works on my PC ;---;

**Comment by DarrenOfficial** [comment]
There's still **alot** of bugs with this changes.

**Comment by SudhanPlayz** [comment]
fix n merge ...

**Comment by DarrenOfficial** [comment]
It's brokey, can't merge. fix complicated

**Comment by SudhanPlayz** [comment]
idc just merge ;_; I can't fix tones of conflicts by you guys adding stuff in v5

**Comment by DarrenOfficial** [comment]
I'm just going to close this for now. Me and toshit#0942 are still trying to bug fix most of v5 commands.
Once most of the bugs & features are completed, I will convert it all to modules.

**Comment by DarrenOfficial** [comment]
Sudhan I changed my mind, just rename the current v5 branch to something else. and make this the main v5 branch

**Comment by DarrenOfficial** [comment]
Im pretty sure only you can do it, cause ur the repo owner

**Comment by jschenke488** [comment]
If this is the correct link, these are the changes between module and v5 https://github.com/SudhanPlayz/Discord-MusicBot/compare/module...v5

**Comment by DarrenOfficial** [comment]
> If this is the correct link, these are the changes between module and v5 [module...v5](https://github.com/SudhanPlayz/Discord-MusicBot/compare/module...v5)

and..?

**Comment by SudhanPlayz** [comment]
;_;

**Comment by SudhanPlayz** [comment]
moudle  in v5 when when

**Comment by DarrenOfficial** [comment]
> module in v5 when when

When i have the brain power to do it

**Comment by SudhanPlayz** [comment]
> > module in v5 when when
> 
> When i have the brain power to do it

plij get power quick

**Comment by SudhanPlayz** [comment]
not adding this to v5

**Pull request closed without merging**
