### PR TITLE
Patching lyrics character limit bug

### PR DESCRIPTION
**Pull request by BioCla**
removed the bug for lyrics going over the embed description character limit

**Please describe the changes this PR makes and why it should be merged:**
removed the bug for lyrics going over the embed description character limit
**Status and versioning classification:**
Completed; v5 commands/slash/lyrics.js

### CODE REVIEW

**Review by DarrenOfficial — APPROVED** [review]
not the best way to do it, but it works...

**Comment by BioCla** [comment]
> not the best way to do it, but it works...

Any feedback or notes for improvement are greatly appreciated as I'm still learning and trying to acquaint myself with JS properly.
How could I have made it better, if you don't mind me asking?

**Comment by BioCla** [comment]
Oh no, I've notice my blunder. This prevents lyrics with under 4096 characters from actually showing up

**Comment by DarrenOfficial** [comment]
> How could I have made it better, if you don't mind me asking?

Pagination (like queue command), that would have been a better solution ig

**Comment by BioCla** [comment]
That's definitely doable. I'll look into implementing it

**Pull request merged**
