### PR TITLE
fix licence name

### PR DESCRIPTION
**Pull request by Monoverde888**

### CODE REVIEW

**Comment by SudhanPlayz** [comment]
Bruh Moment

**Comment by SudhanPlayz** [comment]
Anyways thanks

**Comment by SudhanPlayz** [comment]
I'm merging

**Comment by SudhanPlayz** [comment]
Wait still wrong spelling
the name is `license` LOL

**Comment by Monoverde888** [comment]
uh

**Comment by SudhanPlayz** [comment]
Lol

**Pull request closed without merging**
