### PR TITLE
cheesecake playlist inserted

### PR DESCRIPTION
**Pull request by samarth-ar10**
**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
What tf

**Comment by DarrenOfficial** [comment]
what the hell is this?

**Comment by samarth-ar10** [comment]
I'm sorry. I made a mistake
I thought I was merging in my fork.
Please deny the changes

**Comment by samarth-ar10** [comment]
I truly am sorry about this.

**Pull request closed without merging**
