### PR TITLE
Simple ping command

### PR DESCRIPTION
**Pull request by XstreamSpeed**
**Please describe the changes this PR makes and why it should be merged:**
Simple ping command that every bot should have 

**Status and versioning classification:**
Nodejs v17.8.0

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
Use camelCase please.

**Comment by DarrenOfficial** [comment]
embed1, embed, ect. Is uninformative.

**Comment by BioCla** [comment]
Please check for mismatched parentheses and scopes, seems there's a few syntax errors too.

**Comment by BioCla** [comment]
dunno how to suggest edits to a commit, or if that is even possible so I'll just put this here:
it's untested and just based on what was already done, fixing the small things.
```js
const SlashCommand = require("../../lib/SlashCommand");
const { MessageEmbed } = require("discord.js");

const command = new SlashCommand()
.setName("ping")
.setDescription("View the bot's latency")
.setRun(async (client, interaction, options) => {	
	let msg = await interaction.reply({
		embeds: [new MessageEmbed()
			.setDescription("🏓 | Fetching ping...")
			.setColor("#6F8FAF")
		]
	})
	
	let zap = "⚡"
	let green = "🟢"
	let red = "🔴"
	let yellow = "🟡"
	
	var latState = zap;
	var apiState = zap;
	
	let apiPing = Math.round(client.ws.latPing)
	let latPing = `${Date.now() - msg.createdTimestamp}`
	const uptimeCount = moment.duration(client.uptime).format(" D [days], H [hrs], m [mins], s [secs]");
	
	if (apiPing >= 40 && apiPing < 200) {
		apiState = green;
	} else if (apiPing >= 200 && apiPing < 400) {
		apiState = yellow;
	} else if (apiPing >= 400) {
		apiState = red;
	}
	
	if (latPing >= 40 && latPing < 200) {
		latState = green;
	} else if (latPing >= 200 && latPing < 400) {
		latState = yellow;
	} else if (latPing >= 400) {
		latState = red;
	}
	
	msg.edit({ 
		embeds: [new MessageEmbed()
			.setTitle("🏓 | Pong!")
			.addField("API Latency", `${apiState} | ${apiPing}ms`, true)
			.addField("Message Latency", `${latState} | ${latPing}ms`, true)
			.addField("Uptime", `⏲️ | ${uptimeCount}`, true)
			.setColor("#6F8FAF")
			.setFooter({
				text: `Requested by ${interaction.user.username}`,
				iconURL: (message.author.avatarURL())
			})
		] 
	})	
});
```

**Comment by DarrenOfficial** [comment]
> Please check for mismatched parentheses and scopes, seems there's a few syntax errors too.

This shouldn't happen, @XstreamSpeed Please check your commit / changes first before making a pull request.

**Comment by XstreamSpeed** [comment]
Yeah, all of my recent pull requests are not tested. I don't have much time to do so, I'm preparing for 10th rn.

**Comment by SudhanPlayz** [comment]
this is music bot, why does this needed?

**Comment by DarrenOfficial** [comment]
> this is music bot, why does this needed?

That's what I said

**Comment by DarrenOfficial** [comment]
> Yeah, all of my recent pull requests are not tested. I don't have much time to do so, I'm preparing for 10th rn.

Then don't make those pull request(s), stop wasting maintainers time. If you want to contribute to FOSS. Test 👏🏼  your 👏🏼 commit 👏🏼 first 👏🏼 before 👏🏼 making 👏🏼 a 👏🏼 pull 👏🏼 request.

**Comment by DarrenOfficial** [comment]
I'm just going to close this.

**Comment by XstreamSpeed** [comment]
Alright dawg

**Pull request closed without merging**
