### PR TITLE
new lavalink server

### PR DESCRIPTION
**Pull request by draxya**
I added the lavalink server that I host myself on replit which has private repo and 7/24 uptime (always on).

### CODE REVIEW

**Comment by LewdHuTao** [comment]
replit lavalink is bad

**Comment by JotaroKujo0525** [comment]
Hello, unfortunately, I'll close this for a couple of reasons.

1. As @LewdHuTao said, replit lavalink is bad and quite unstable
2. We are not sure if this will last, if this goes down, the discord server will explode (trust me)
3. Also, in the mastter of shutdown, we have no means of contacting you, and even if we do, it's exhausting to actually do this everytime

We can only accept stable lavalinks such as `lava.link` but unfortunately this will increase the amount of requests they receive so we encourage the people on the discord server to host their own lavalink or choose lavalink in [here](https://lavalink-list.darrennathanael.com)

**Comment by JotaroKujo0525** [comment]
still, thank you for your pr

**Comment by MiracleCherryPie** [comment]
Mine have powerful lavalink server but the jar got error when I going to search from YT

**Comment by MiracleCherryPie** [comment]
Anyway how y'all detect if the lavalink is hosted on replit or not @JotaroKujo0525 @LewdHuTao

**Comment by JotaroKujo0525** [comment]
port.

**Comment by MiracleCherryPie** [comment]
Wait, it also might not be accurate
He might run lavalink as root listening on port 443
Try lookup the DNS and check the IP address

**Comment by MiracleCherryPie** [comment]
Wait me dum
I don't see replit

**Comment by LewdHuTao** [comment]
i usually check the port and if i want to confirm it was replit lavalink, i put the lavalink info into my lavalink status thingy and it will shows the lavalink specs, if its only have 1 core and only 260mb of ram it is repl lavalink

**Pull request closed without merging**
