### PR TITLE
Fixed YouTube Command

### PR DESCRIPTION
**Pull request by jnsp-vsc**
Since the package causes error if ur on replete and dont have node v14

**Please describe the changes this PR makes and why it should be merged:**
I made the YouTube command work without Sudhans package, so that people won't have the issue with the acitivityinvite and stuff, slash and normal works fine now. A package was not needed for this command to begin with which is why it wasn't working for people who wanted to use the command

**Status and versioning classification:**

### CODE REVIEW

**Comment by joeyk710** [comment]
I think this will work fine, but it's up to Sudhan to decide on what he wants to do

**Comment by SudhanPlayz** [comment]
No ;-;

**Review by SudhanPlayz — CHANGES_REQUESTED** [review]
PR them into the package instead of this

**Comment by jnsp-vsc** [comment]
> PR them into the package instead of this

No >:(

**Comment by SudhanPlayz** [comment]
> > PR them into the package instead of this
> 
> No >:(

Oki then I will do sometime later ;-;

**Pull request closed without merging**
