### PR TITLE
Update botconfig.js

### PR DESCRIPTION
**Pull request by sawadalla**
**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**

### CODE REVIEW

**Comment by LewdHuTao** [comment]
wtf

**Comment by urbels** [comment]
Sharing is caring. :)

**Comment by JotaroKujo0525** [comment]
i-

**Comment by JotaroKujo0525** [comment]
WTF man, close this rn

**Comment by sawadalla** [comment]
@JotaroKujo0525 can you please contact github support to get this deleted? Thanks

**Comment by JotaroKujo0525** [comment]
It should be fine if he regenerated his token

**Pull request closed without merging**
