### PR TITLE
Improve Controller & Clean all leftover

### PR DESCRIPTION
**Pull request by KiyoshiKunCool**
* Update Controller
* Delete 2 embed "Queue End" and "Disconnected"
All tested and working fine :3

### CODE REVIEW

**Comment by JotaroKujo0525** [comment]
there very jice

**Comment by JotaroKujo0525** [comment]
I'll test this on my laptop and see if it works

**Comment by DarrenOfficial** [comment]
I'll test this right away, I'll let you know in a moment if I found any issue

**Review by DarrenOfficial — APPROVED** [review]
everything works as expected, thank-you for your contribution <3

**Comment by JotaroKujo0525** [comment]
ohh nice new contributor

**Pull request merged**
