### PR TITLE
Added move command

### PR DESCRIPTION
**Pull request by poppin-fresh**
**Please describe the changes this PR makes and why it should be merged:**

Requested in  #400 
This command will let you move a track from the queue to a specified position and shifts the rest down. 

Supports SlashCommand.
Tested and working, has checks for invalid args to prevent crashing. 

**Status and versioning classification:**

### CODE REVIEW

**Review by Kakarot-0690 — DISMISSED** [review]
check

**Comment by Kakarot-0690** [comment]
Do we really require this?

**Comment by poppin-fresh** [comment]
> 
> 
> Do we really require this?

Why wouldn't you want a new useful feature? If it doesn't suit your needs you don't need to use it.

**Comment by Kolapsicle** [comment]
> 
> 
> Do we really require this?

Playlist manipulation is pretty handy when multiple people are requesting music. Is there any reason why it shouldn't be available?

**Comment by Kakarot-0690** [comment]
> > Do we really require this?
> 
> Why wouldn't you want a new useful feature? If it doesn't suit your needs you don't need to use it.
> 
> EDIT: Not sure what the point of your review request is, accident?

nope not an accident, just want joe to check once before I can merge : )

**Comment by Kakarot-0690** [comment]
Works fine for me yet I will just verify once

**Pull request merged**
