### PR TITLE
Fixed player doesn't stop when autoqueue enabled

### PR DESCRIPTION
**Pull request by Saud-97**
**Please describe the changes this PR makes and why it should be merged:**
Fixed a bug where a player doesn't stop when autoqueue is enabled 

**This is related to manual user stop action doesn't work atm since it only does player.stop instead of player.destroy to accommodate for 24/7 players hence stopping autoqueue is needed in this case..**

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
that's the point? autoQueue automatically add's song to queue to make sure the player never stops and keep adding song?

**Comment by Saud-97** [comment]
> that's the point? autoQueue automatically add's song to queue to make sure the player never stops and keep adding song?

It doesn't stop even when manually trying to stop it using controller stop action or /stop action.

**Comment by BioCla** [comment]
We should make a list of all these small but breaking changes and just set them up as a project. Maybe have them as a separate release later on. like a v5.1
I mean. all these things are cool, but they require a lot of messing around with the structure.
I don't see how these changes are necessary as the bot is working fine on my end (referring to other issues too)

**Comment by Saud-97** [comment]
> We should make a list of all these small but breaking changes and just set them up as a project. Maybe have them as a separate release later on. like a v5.1 I mean. all these things are cool, but they require a lot of messing around with the structure. I don't see how these changes are necessary as the bot is working fine on my end (referring to other issues too)

Well this is why Github milestones exist. This issue can stay open and be marked as a v5.1 milestone.

Also you have never faced this bug either because you used /stop and 247 is off then the player will destroy anyway so it won't happen. Or you didn't use controller stop button hence you never noticed it happening.

**Comment by Saud-97** [comment]
Rebased.

**Comment by Saud-97** [comment]
This is related to manual user stop action doesn't work atm since it only does player.stop instead of player.destroy to accommodate for 24/7 players hence stopping autoqueue is needed in this case to actually make the bot stop **instead of ignoring user command and treating it as a next action wrongly**.

**Review by DarrenOfficial — APPROVED** [review]

**Pull request merged**
