### PR TITLE
Avoid Confusion

### PR DESCRIPTION
**Pull request by Kakarot-0690**
Many people are writing there hosts inside () and end up getting an error so remove it to avoid confusion

**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
smort

**Comment by DarrenOfficial** [comment]
smort

**Comment by DarrenOfficial** [comment]
smort

**Comment by Kakarot-0690** [comment]
> smort

I fstg, I am so done with these ppl in support writing there host like host: "(wtf.shit.co)"

**Pull request merged**
