### PR TITLE
fix grab command crashing bot if nothing playing

### PR DESCRIPTION
**Pull request by poppin-fresh**
**Please describe the changes this PR makes and why it should be merged:**

  Fixes grab command crashing the bot if no song is playing

**Status and versioning classification:**

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
have you tested it?

**Review by DarrenOfficial — CHANGES_REQUESTED** [review]
Slash command hasn’t been changed. line 61 - 62

**Comment by poppin-fresh** [comment]
> 
> 
> have you tested it?

Yeah, I don't push without testing locally. 

> 
> 
> Slash command hasn’t been changed. line 61 - 62

Slash command doesn't crash it due to line 82

**Comment by DarrenOfficial** [comment]
looks good

**Review by DarrenOfficial — APPROVED** [review]

**Pull request merged**
