### PR TITLE
`Shortening`

### PR DESCRIPTION
**Pull request by BioCla**
**Please describe the changes this PR makes and why it should be merged:**
Step one of the `shortening`: A project for making the existing code shorter and cleaner, while integrating pre existing utilities which never got to be used (util/getChannel.js) ;-;
**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes

**NOTES:**
The changes presented here bring a lot to the table, apart from the usage of the pre existing `.util/getChannel.js` also numerous little mods have been made to make the code cleaner and more effective. 
This is not valid for the indentation as I was told to do so against my will.
Have fun finding all the bugs that may or may not exists within this PR.
The commands have been tested thoroughly enough to see if they actually work, but given this is a big commit there still may be some things we forgot. If you do find anything be sure to let us know through the [discord support server](https://discord.gg/sbySMS7m3v) or a [new issue](https://github.com/SudhanPlayz/Discord-MusicBot/issues/new?assignees=&labels=s%3A+unverified%2C+type%3A+bug&template=bug_report.md&title=Shortening%20bug)!

### CODE REVIEW

**Comment by BioCla** [comment]
there will be more changes being added to this in order to `shortify` each command, so marking this as a draft

**Comment by JotaroKujo0525** [comment]
this repo is being flooded by prs ngl, anw i praise your english spellings here, you did a nice job

**Review by BioCla — COMMENTED** [review]
The changes presented here bring a lot to the table, apart from the usage of the pre existing `.util/getChannel.js` also numerous little mods have been made to make the code cleaner and more effective. 
This is not valid for the indentation as I was told to do so against my will.
Have fun finding all the bugs that may or may not exists within this PR.
The commands have been tested thoroughly enough to see if they actually work, but given this is a big commit there still may be some things we forgot. If you do find anything be sure to let us know through the discord support server or a new issue!

**Comment by SudhanPlayz** [comment]
There are too many changes. The code is working fine?

**Comment by BioCla** [comment]
> There are too many changes. The code is working fine?

Yes, everything has been tested with help from fellow contributors while we were in a VC. As far as the functionalities of each commands goes everything is working as expected

**Comment by SudhanPlayz** [comment]
is it ready for merge or still needs commit?

**Comment by BioCla** [comment]
> is it ready for merge or still needs commit?

everything is ready

**Comment by SudhanPlayz** [comment]
image
Thanks for the contribution!

**Pull request merged**
