### PR TITLE
Bot can auto leave after a given time

### PR DESCRIPTION
**Pull request by LumiDevLabs**
**Please describe the changes this PR makes and why it should be merged:**

Added the ability to automatically let the bot leave the voice channel, after being alone for more than a given time.
The time can be changed in the bot config, or the module can be comlpetely disabled.

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- This PR changes the library's interface (methods or parameters added)

Discord_kKNMrMb0B2

### CODE REVIEW

**Review by C-EO — CHANGES_REQUESTED** [review]
I would suggest increasing the time to match the v5 setting of autoleave.

I mean 30 seconds! It becomes quite tiresome to have to summon the bot to the VC every single time.

**Comment by LumiDevLabs** [comment]
The default setting of auto leave is in the v5 version, on 30 seconds too

**Comment by C-EO** [comment]
> The default setting of auto leave is in the v5 version, on 30 seconds too

@nikdraws  I think making it 10 or 30 minutes will be okay too.

**Comment by C-EO** [comment]
I have no problem with it, just that the timing is unreal. What if I left the bot to get a cup of tea for two minutes and I expect it to still be connected to the VC?

**Comment by Assassin654** [comment]
> The default setting of auto leave is in the v5 version, on 30 seconds too

There is no default setting for the v5

In v5 it will leave the instant everyone is gone unless you configure it with 24/7, in which case you can configure the leave time.

**Comment by LumiDevLabs** [comment]
> I have no problem with it, just that the timing is unreal. What if I left the bot to get a cup of tea for two minutes and I expect it to still be connected to the VC?

I added the ability to choose your own time, before disconnecting

**Comment by C-EO** [comment]
@Blis204 Now you're talking. Thanks for making the change

**Review by sussyname — APPROVED** [review]

**Comment by Antoohh** [comment]
there is one problem, whenever the bot is left alone in the channel, just someone connects the bot will play the music again but after the indicated time it will disconnect anyway.

**Comment by C-EO** [comment]
@Antoohh The problem is at your end then. @Blis204 covered your issue in the code as he committed it.

**Review by C-EO — APPROVED** [review]

**Pull request closed without merging**
