### PR TITLE
Fixed some stuffs for replit docs

### PR DESCRIPTION
**Pull request by JotaroKujo0525**
**Please describe the changes this PR makes and why it should be merged:**
Fixed the icon stuff and also added some more instruction as the current one just clones the `master`  tree.
**Status and versioning classification:**
Uh just gonna leave this blank

### CODE REVIEW

**Comment by JotaroKujo0525** [comment]
just tell me if there's anything wrong thx and bye

**Comment by JotaroKujo0525** [comment]
oh uh just now, i added a side note for those who are switching from v4 to v5

**Comment by SudhanPlayz** [comment]
#final ???

**Comment by JotaroKujo0525** [comment]
Yes, https://github.com/SudhanPlayz/Discord-MusicBot/blob/v5/documentation/docs/installation/replit.md#final

**Comment by JotaroKujo0525** [comment]
Is there a problem there? Should I replace it?

**Comment by DarrenOfficial** [comment]
mm final

**Comment by DarrenOfficial** [comment]
closed as duplicated /s

**Comment by DarrenOfficial** [comment]
lol

**Pull request merged**
