### PR TITLE
Development

### PR DESCRIPTION
**Pull request by SudhanPlayz**

### CODE REVIEW

**Comment by SudhanPlayz** [comment]
REEEEEEEEEEEEEEEEEEEE

**Comment by SudhanPlayz** [comment]
Someone resolve confilts ;-;

**Comment by kaaax0815** [comment]
I dont have rights to do @SudhanPlayz I can help you if you want, but i wont help if i but time to the project then then get rejected iykyk

**Comment by joeyk710** [comment]
> I dont have rights to do @SudhanPlayz I can help you if you want, but i wont help if i but time to the project then then get rejected iykyk

I appreciate you offering to help! If you find any bugs, by all means please create a pull request so we can review it!

**Pull request merged**
