### PR TITLE
REPLIT: nodejs 16+

### PR DESCRIPTION
**Pull request by dottodottoo**
added this because i noticed you need to install nodejs 16+ every time you restart your bot

### CODE REVIEW

**Comment by JotaroKujo0525** [comment]
you need to put every package right now that you need to replit.nix xd

**Review by SudhanPlayz — APPROVED** [review]
Have you tested?

**Comment by SudhanPlayz** [comment]
> you need to put every package right now that you need to replit.nix xd

Just needed nodejs as deps since it's nix package manager and not npm

**Comment by dottodottoo** [comment]
> Have you tested?

yea but you have to do npm i in console if you run the bot for the first time not like in v4 it’ll auto do npm i

**Pull request merged**
