### PR TITLE
Revert "V5"

### PR DESCRIPTION
**Pull request by ItzCuteAkemi**
Reverts SudhanPlayz/Discord-MusicBot#908

### CODE REVIEW

**Comment by XstreamSpeed** [comment]
> wait, I think it's bad idea though

Thank you guy literally thought he could implement his own bot with random shit all across, thank god it was reverted

**Comment by DarrenOfficial** [comment]
you're doing god works for fixing this mess.

**Comment by DarrenOfficial** [comment]
who approve this commit in the first place?!?

**Comment by DarrenOfficial** [comment]
> you're doing god works for fixing this mess.

and devil works for approving this mess in the first place.

**Comment by DarrenOfficial** [comment]
Please always test it before you commit/approve request, you don't want broken code in the repo. if you don't have time or the capacity to test it just wait for someone else. there are plenty of reviewers I myself included, @BioCla, @SudhanPlayz, @Neko-Life and many more. if you don't know if the code will work or not consider asking for advice from those people I mentioned above. they're most likely more than happy to help you.

Remember, Test -> Make sure it works -> Push to prod.

**Comment by Saud-97** [comment]
@DarrenOfficial can you please squash these two commits? I can't sync my fork because the history reverted all my changes as part of the commits. 

Just squish this revert with the one before it or delete them from history then force-push. The history is broken atm and I can't sync cuz of this.

**Pull request merged**
