### PR TITLE
Website improvements

### PR DESCRIPTION
**Pull request by CodeKid0**
**Please describe the changes this PR makes and why it should be merged:**

Changed website color pallete and some icons.
Also updated readme.md

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by CodeKid0** [comment]
funni pr number

**Comment by joeyk710** [comment]
Did you test this?

**Comment by CodeKid0** [comment]
Yeah

**Review by SudhanPlayz — APPROVED** [review]
Thanks for the contribution

**Comment by CodeKid0** [comment]
> Thanks for the contribution

No problem

**Pull request merged**
