### PR TITLE
Update: Copyright

### PR DESCRIPTION
**Pull request by jessej-samuel**
Updated copyright year from 2021 to 2022 in a bunch of places

- This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
I think it's best to just remove the year completely.

**Comment by jessej-samuel** [comment]
How about I make it dynamic? It updates itself every year.

**Comment by DarrenOfficial** [comment]
No that wont be necessary, as I've planned to remove the year on license & everywhere else anyway

**Comment by jessej-samuel** [comment]
oooh ok then 👍

**Review by DarrenOfficial — APPROVED** [review]

**Pull request merged**
