### PR TITLE
Revert to ed1812f

### PR DESCRIPTION
**Pull request by JotaroKujo0525**
Fix of #923

### CODE REVIEW

**Comment by JotaroKujo0525** [comment]
Also, please don't hesitate to test it first, I tested it and its working fine for me, but to be sure, test it yourself thanks

**Comment by JotaroKujo0525** [comment]
Also who commited the `kickstartReplit.sh` in master, its just a copy of `kickstartReplit.sh` from v5, v5 is so different from master, like, the `npm run deploy`, you don't need to deploy commands in master branch and there's not even a deploy script on package.json

**Review by DevAmiyo — APPROVED** [review]

**Comment by JotaroKujo0525** [comment]
Aight, instead of fixing all the issues, I've decided to just revert the changes. Upgrading to discord.js V13 is kinda useless since we have v5. V5 is already stable so they can just use that instead of breaking the master branch

**Comment by JotaroKujo0525** [comment]
Also removed Darren's lavalink from botconfig.js

**Comment by ItzCuteAkemi** [comment]
> Also removed Darren's lavalink from botconfig.js

shall I remove it? darren's lavalink is bad anyway

**Comment by ItzCuteAkemi** [comment]
oh nvm you remove that
but ppl will invade support channel for lavalink not connected error

**Comment by JotaroKujo0525** [comment]
Mobile or pc?

**Review by ItzCuteAkemi — APPROVED** [review]
this is fine as many bot hosted on replit free plan is not token leaked

**Comment by JotaroKujo0525** [comment]
Had to really do this, so many bugs with the current version.

**Comment by JotaroKujo0525** [comment]
> Why don't just drop this version and working on improving v5 instead?
> 
> Anyway, LGTM.

About this idea, Sudhan will decide, but I think it's a pretty great idea as v5 is complete now

**Pull request merged**
