### PR TITLE
Using replit.nix instead of downloading nvm

### PR DESCRIPTION
**Pull request by ItzCuteAkemi**
**Please describe the changes this PR makes and why it should be merged:**
The replit.nix environment is more effective and less-consuming repl storage instead of downloading nvm and install nodejs 16 from it.

Steps to produce:
1. Create new repl and Import from Github
2. Use https://github.com/ItzCuteAkemi/Discord-MusicBot as repository
3. go into version control and change from master to v5
4. fill config.js
5. type `node -v` to see the node version
6. ??
7. then run `bash ./kickstartReplit.sh` to configure the bot

Results:
Screenshot_2022-08-01_23-01-23

Don't mind cdf5f0b since it's dead lavalink. Just remove them if this is merged

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
Have you tested music playback? specifically spotify

**Comment by ItzCuteAkemi** [comment]
Didn't tried yet, I will try tomorrow with my bot

**Comment by JotaroKujo0525** [comment]
the problem with nodejs-16_x is it doesnt give the exact node version,as you can see it giges 16.7.0.

you can also try running this, you'll get an error message like `Failed to renew Spotify Token: <whatever reason>`

**Comment by JotaroKujo0525** [comment]
i've also thought of this for a while and decided to just use nvm to make things easier

**Comment by JotaroKujo0525** [comment]
aight,er just discovered something, @ItzCuteAkemi let's discuss it in the discord server

**Review by JotaroKujo0525 — CHANGES_REQUESTED** [review]
in your `.replit` file
```bash
# running kickstartReplit.sh is unnecessary because 
# its included in the tutorial
# and they only need to run it once
run = "node index.js" 
language = "Bash"

# channel specification for nix
# you need to do this in order
# to get the proper node version 
[nix]
channel = "stable-22_05"
```

**Comment by JotaroKujo0525** [comment]
remaking this pull request

**Pull request closed without merging**
