### PR TITLE
Added Stop Command

### PR DESCRIPTION
**Pull request by Pro-Nil**
**Please describe the changes this PR makes and why it should be merged:**
This PR adds stop command to the bot. I guess a stop command is extremely necessary for a discord bot .

- This PR has been thoroughly tested .

### CODE REVIEW

**Comment by BioCla** [comment]
image
this is identical to the leave command

**Comment by DevAmiyo** [comment]
> This PR adds stop command to the bot. I guess a stop command is extremely necessary for a discord bot 

It aleady exists. [`commands/slash/leave.js`](https://github.com/SudhanPlayz/Discord-MusicBot/blob/v5/commands/slash/leave.js)
stop/leave/disconnect are basically the same thing.

**Comment by Saud-97** [comment]
This doesn't account for the case when 247 is enabled. Destroy will kick the bot.

**Comment by Pro-Nil** [comment]
hmmm okay

**Pull request closed without merging**
