### PR TITLE
Song Titles are not escaping formatting Fix, AutoPause Fix and AutoQueue on Skip Function Support

### PR DESCRIPTION
**Pull request by GazorHuman**
** Please explain the changes this PR makes and why it should be combined:**

**This PR has been tested multiple times**

This PR fixes an issue where song titles were not passing formatting across different embeds and also fixes an issue where song titles could change the clickable song title link across different embeds. 
**Consequences: If a song title has "[" or "]" characters in it, those characters will be converted to "none", in other words, they will be removed.**

This PR also fixes an issue with AutoPause, so the issue is that when the player is paused and the user mutes/unmutes themselves, the player will automatically resume and that shouldn't happen.

The original issue about song titles was created [here](https://github.com/SudhanPlayz/Discord-MusicBot/issues/1070) by [MerlinDaWizard](https://github.com/MerlinDaWizard)

New on 2/11/2022, Added AutoQueue Support on Skip function #1113, so if AutoQueue is ON the song can be skipped.

**Version status and classification:**

- This PR includes breaking changes (method removed or renamed, parameter moved or removed) 
- I know how to update the typing and have done so, or the typing does not need to be updated
- The code changes have been tested against the Discord API, or there are no code changes

### CODE REVIEW

**Comment by XstreamSpeed** [comment]
instead of doing 
```js
title.replace(/\]/g," ")
```

why not do 

```js
title.replace(/\]/g,"")
```

it prevents the titles from looking weird because of a space

**Comment by GazorHuman** [comment]
> instead of doing 
> 
> ```js
> 
> title.replace(/\]/g," ")
> 
> ```
> 
> 
> 
> why not do 
> 
> 
> 
> ```js
> 
> title.replace(/\]/g,"")
> 
> ```
> 
> 
> 
> it prevents the titles from looking weird because of a space

Oops!, i just realised about the space. thanks for reminding!

**Comment by XstreamSpeed** [comment]
> > instead of doing
> > ```js
> > title.replace(/\]/g," ")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > why not do
> > ```js
> > title.replace(/\]/g,"")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it prevents the titles from looking weird because of a space
> 
> Oops!, i just realised about the space. thanks for reminding!

no worries mate

**Review by adityaghub — APPROVED** [review]
i want these

**Comment by GazorHuman** [comment]
Added AutoQueue Support on Skip Function

**Comment by DarrenOfficial** [comment]
Thank you for your contribution <3; sorry I couldn't get this review sooner. I took a break from this project a long time ago.

**Review by DarrenOfficial — APPROVED** [review]

**Pull request merged**
