### PR TITLE
Add discord.js V13 support

### PR DESCRIPTION
**Pull request by TwixGamer00**
**Please describe the changes this PR makes and why it should be merged:**
I've updated the discord.js version to V13, which is more stable.

**Status and versioning classification:**
Only problem is that the youtube command doesnt work because it isnt supported for V13, but i dont think its that big of a deal

### CODE REVIEW

**Comment by BioCla** [comment]
I feel sorry being this late to this... but you see, DJS 13 is being used in the [v5](https://github.com/SudhanPlayz/Discord-MusicBot/tree/v5) branch already, as you may know from the response I gave in your related issue post.

I'm afraid this PR might not be merged for that reason.
If you want though, you should look through the v5 and see if you want to contribute there! TY for the time and effort!

**Comment by XstreamSpeed** [comment]
I feel you man

**Comment by DarrenOfficial** [comment]
Actually good commit, unfortunate that v5 exist. (also version 4.2.0 nice).

@SudhanPlayz We should merge this for the final nail in the coffin.

**Comment by SudhanPlayz** [comment]
> Actually good commit, unfortunate that v5 exist. (also version 4.2.0 nice).
> 
> @SudhanPlayz We should merge this for the final nail in the coffin.

the pr has conflicts, we will merge it if its working good enough

**Comment by TwixGamer00** [comment]
> > Actually good commit, unfortunate that v5 exist. (also version 4.2.0 nice).
> > @SudhanPlayz We should merge this for the final nail in the coffin.
> 
> the pr has conflicts, we will merge it if its working good enough

I removed the package-lock, causing the conflict

**Comment by TwixGamer00** [comment]
Also merged that other PR with the dotenv thingie

**Review by SudhanPlayz — APPROVED** [review]

**Comment by TwixGamer00** [comment]
> If you want though, you should look through the v5 and see if you want to contribute there! TY for the time and effort!

Anything specific i can do?

**Review by DarrenOfficial — APPROVED** [review]
Looks good

**Pull request merged**
