### PR TITLE
Notv4

### PR DESCRIPTION
**Pull request by notziru**
added discord together, added all discord activities instead of just poker and cleaned up youtube.js

### CODE REVIEW

**Comment by txj-xyz** [comment]
Why would you use another package for this?

Wouldn't it be easier to not rely on someone else to keep the code working?

Seems useless, you also removed all of the checks for VC and rely on the lib to do that.

**Comment by notziru** [comment]
> Why would you use another package for this?
> 
> Wouldn't it be easier to not rely on someone else to keep the code working?
> 
> Seems useless, you also removed all of the checks for VC and rely on the lib to do that.

discord-together is already included and being used and only vc check I removed was be in same vc seems not needed

**Comment by DarrenOfficial** [comment]
No this will not be merged because All of those activity are soon going to be put behind server boost. so adding them would be useless.

**Comment by DarrenOfficial** [comment]
also I forgot to remove the youtube.js & poker on this branch lol

**Comment by DarrenOfficial** [comment]
As you can see here I've removed those "activity" like amonth ago https://git.darrennathanael.com/DarrenOfficial/DiscordMusic/commit/da8928f5b4945991aad23711da668f0a795e472e
https://git.darrennathanael.com/DarrenOfficial/DiscordMusic/commit/fa9fab81ab29f20d92cec325b64104d7ceb3fdc6

**Pull request closed without merging**
