### PR TITLE
Add youtube together

### PR DESCRIPTION
**Pull request by JotaroKujo0525**
**Please describe the changes this PR makes and why it should be merged:**
Added a youtube together command just like v4
**Status and versioning classification:**
node: 16.13.1

### CODE REVIEW

**Comment by JotaroKujo0525** [comment]
oh i forgor the package

**Comment by DarrenOfficial** [comment]
didn't discord implement this as a feature already? also I tested this on a new server and it just says invalid link but it works on some existing server.

I don't think it's a good idea to add this.

**Review by SudhanPlayz — APPROVED** [review]

**Comment by DarrenOfficial** [comment]
> > didn't discord implement this as a feature already? also I tested this on a new server and it just says invalid link but it works on some existing server.
> > I don't think it's a good idea to add this.
> 
> Oh, did discord already implement this? Also the cause of the invalid link is not giving the bot "Create Invite Permission" I forgor to add

It has admin perms

**Comment by DarrenOfficial** [comment]
> > didn't discord implement this as a feature already? also I tested this on a new server and it just says invalid link but it works on some existing server.
> > I don't think it's a good idea to add this.
> 
> Oh, did discord already implement this? 


Yes.

**Comment by DarrenOfficial** [comment]
only in some server but they're slowly rolling it out to all.

**Comment by JotaroKujo0525** [comment]
kk ig this won't be needed at all

**Pull request closed without merging**
