### PR TITLE
Adding require("dotenv") to deploy scripts

### PR DESCRIPTION
**Pull request by pheeef**
### Fixing deploy scripts to respect load .env config properly.

When using a .env file it wouldn't load the token because it's just run by js and not bundled/interpreted by webpack or similar. 

### Solution

I've included `const dotenv = require("dotenv").config();` in all the 3 deploy scripts.
After that addition the commands were sucessfully deployed to the discord api.

## Status and versioning classification:

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

# Important.

- Write in camelCase, not snake_case.
- Do not push to master/main without testing your changes first, make a branch
  if you have to.

### CODE REVIEW

**Review by Assassin654 — COMMENTED** [review]
this is not needed. This bot by default does not use .env anywhere.

**Comment by Phillackinger** [comment]
@Assassin654 
> this is not needed. This bot by default does not use .env anywhere.

It does - Look at the config.js file

```js
module.exports = {
	cmdPerPage: 10, //- Number of commands per page of help command
	token: process.env.token || "", //- Bot's Token
	clientId: process.env.clientId || "", //- ID of the bot
	clientSecret: process.env.clientSecret || "", //- Client Secret of the bot
[..]
};
```

**Comment by Assassin654** [comment]
> @Assassin654
> 
> > this is not needed. This bot by default does not use .env anywhere.
> 
> It does - Look at the config.js file
> 
> ```js
> module.exports = {
> 	cmdPerPage: 10, //- Number of commands per page of help command
> 	token: process.env.token || "", //- Bot's Token
> 	clientId: process.env.clientId || "", //- ID of the bot
> 	clientSecret: process.env.clientSecret || "", //- Client Secret of the bot
> [..]
> };
> ```
> 
> It also a feature I use because I want to have a unified config file for multiple bots with different tokens so my config file is a Sym-Link and the tokens are stored in each bot-folders .env file

my bad. I do not use .env for this bot. but in this case, all you need is the dotenv import in the config.js file that reads the token. not all three deploy scripts. that should fix the issue.

**Comment by Phillackinger** [comment]
> my bad. I do not use .env for this bot. but in this case, all you need is the dotenv import in the config.js file that reads the token. not all three deploy scripts. that should fix the issue.

Thanks for your feedback! This was just my quick and dirty fix to get it working :] - i'll change the import to the config load file.

**Pull request merged**
