### PR TITLE
Fixes #897

### LINKED ISSUE #897: Paused but goes playing when new user join
**Please describe the problem you are having in as much detail as possible:**
When the bot is paused and new user (another bot) join the vc I'm startled because this bot suddenly resumed the paused playback even there's no one invoked the resume/play command. Did the bot startled about new user joining and frantically resume the playback? Was it nervous? Was it just a panic attack? I don't know but I'm afraid and concerned this bot gonna get stroke because of sudden heart attack.

**Include a reproducible code sample here, if possible:**
```js
null
```

**Further details:**

- discord.js version: 13.8.0
- Node.js version: v18.3.0
- Operating system: Arch Linux x86_64 kernel 5.18.2-arch1-1
- Priority this issue should have – please be realistic and elaborate if possible: Unimportant

**Relevant client options:**

- partials: none
- gateway intents: 
```js
      intents: [
        Intents.FLAGS.GUILDS,
        Intents.FLAGS.GUILD_VOICE_STATES,
        Intents.FLAGS.GUILD_MESSAGES,
      ]
```
- other: my bot token is `ODY9OCAwFTYzOBIzNKc5GOU2.G37L_l.1D8pElIZUpQAGiDsCZpbf9oePKgjnVugcJEOv0`, bot username: Amelio#8327
- Commit hash: 56015113f22cc2346e1647a2a8212227233cf915

### PR DESCRIPTION
**Pull request by Saud-97**
**Please describe the changes this PR makes and why it should be merged:**
Fixes #897

**Status and versioning classification:**

- I know how to update typings and have done so, or typings don't need updating
- Code changes have been tested against the Discord API, or there are no code changes

### CODE REVIEW

**Comment by Neko-Life** [comment]
I suggest refactor this system to track whether the player was paused manually by the user or paused because user left the vc, not based on user count.

**Comment by Saud-97** [comment]
> I suggest refactor this system to track whether the player was paused manually by the user or paused because user left the vc, not based on user count.

Open an issue and create a suggestion. This PR is only for fixing the bug.

**Review by DarrenOfficial — CHANGES_REQUESTED** [review]
I suggest refactor this system to track whether the player was paused manually by the user or paused because user left the vc, not based on user count. - @Neko-Life

**Comment by Saud-97** [comment]
> I suggest refactor this system to track whether the player was paused manually by the user or paused because user left the vc, not based on user count. - @Neko-Life

I have tried doing so initially but I couldn't find a way to correctly detect this without causing bugs. Also the player is getting paused and resumed based on other conditions such as when server muted / unmuted.  This would require changing design which I think is something you would need to decide upon.

**Comment by Saud-97** [comment]
Close this if current fix doesn't satisfy your requirements.

**Review by DarrenOfficial — APPROVED** [review]

**Comment by DarrenOfficial** [comment]
rebase the commit so I could merge it

**Comment by Saud-97** [comment]
Done

> rebase the commit so I could merge it

**Review by Neko-Life — APPROVED** [review]
LGTM

**Pull request merged**
