### PR TITLE
Why you do this

### PR DESCRIPTION
**Pull request by Neko-Life**
**Please describe the changes this PR makes and why it should be merged:**
Why you do this? This make it hard to debug. Have you ever read the error thrown by it?

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
10 commits' for 2 file changes 🫠

**Review by DarrenOfficial — APPROVED** [review]

**Comment by Neko-Life** [comment]
I did it one word of code per commit. Your welcome.

**Comment by ItzCuteAkemi** [comment]
nvm

**Comment by Neko-Life** [comment]
> @Neko-Life @DarrenOfficial did yall test the code before push it?

Oh yeah right forgot to test this, I believe this commit causes #1000. RIP those shrimp's brain devs

**Comment by LewdHuTao** [comment]
> > @Neko-Life @DarrenOfficial did yall test the code before push it?
> 
> Oh yeah right forgot to test this, I believe this commit causes #1000. RIP those shrimp's brain devs

#1000 still use v4 so ig it have nothing to do with this pr

**Comment by Neko-Life** [comment]
> > > @Neko-Life @DarrenOfficial did yall test the code before push it?
> > 
> > 
> > Oh yeah right forgot to test this, I believe this commit causes #1000. RIP those shrimp's brain devs
> 
> #1000 still use v4 so ig it have nothing to do with this pr

hoW can you be so suRE?

**Comment by LewdHuTao** [comment]
> > > > @Neko-Life @DarrenOfficial did yall test the code before push it?
> > > 
> > > 
> > > Oh yeah right forgot to test this, I believe this commit causes #1000. RIP those shrimp's brain devs
> > 
> > 
> > #1000 still use v4 so ig it have nothing to do with this pr
> 
> hoW can you be so suRE?

look at the console only v4 register slash everytime bot restart

**Comment by JotaroKujo0525** [comment]
yep its v4

**Comment by Neko-Life** [comment]
No way that's impossible!

**Pull request merged**
