### PR TITLE
Create guildleave.js

### PR DESCRIPTION
**Pull request by Assassin654**
**Please describe the changes this PR makes and why it should be merged:**
allows bot owners to view guilds the bot is in, and additionally, allows you to leave the guild.

something not entirely necessary, but since the bot is meant to be kept small & private, I thought it would be nice to have a command to leave guilds/servers.

**Status and versioning classification:**
Code changes have been tested against the Discord API, or there are no code changes
I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by adityaghub** [comment]
it was needed btw can you do embed thing? rn its look so messed up

**Comment by Assassin654** [comment]
> 

what do you mean it looks so messed up? on my end, it looks fine. provides the guild name then id.

**Comment by DarrenOfficial** [comment]
Why is this needed? This is a discord music bot, not a moderation or utility bot. I don't understand why we need a command to leave a guild.

**Comment by Assassin654** [comment]
> Why is this needed? This is a discord music bot, not a moderation or utility bot. I don't understand why we need a command to leave a guild.

It is not needed as I said. But it is nice to have if you want to make the bot leave a server you're not in/ have perms in, as it is not supposed to be a public bot. It allows you to more easily control that.

**Comment by DarrenOfficial** [comment]
I see; I'll test this first to see if everything works as intended; I will get this merged asap

**Pull request merged**
