### PR TITLE
Make website URL optional

### PR DESCRIPTION
**Pull request by Neko-Life**
**Please describe the changes this PR makes and why it should be merged:**
This is so annoying it's asking me for a domain every time I'm booting it up!

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by XstreamSpeed** [comment]
why can't you open pull requests like normal people do, why this whole massive array of commits, put the commits necessary per pull request, for this pull request, its "Do not start server if website isn't configured".

**Comment by XstreamSpeed** [comment]
> why can't you open pull requests like normal people do, why this whole massive array of commits, put the commits necessary per pull request, for this pull request, its "Do not start server if website isn't configured".

The least you can do is fork the v5 branch and put the commits there

**Comment by Neko-Life** [comment]
Too much effort for a dead project mate. Making 12 commit to change one
line is already tiring, you don't even wanna change it.

**Comment by Neko-Life** [comment]
Alright so @XstreamSpeed see me merge these PR.
I'm gonna delete my fork and do as you say, maybe tomorrow.
Or forever.

**Pull request merged**
