### PR TITLE
Fiz replit v5 issues again

### PR DESCRIPTION
**Pull request by JotaroKujo0525**
**Please describe the changes this PR makes and why it should be merged:**
This pull request solves the issue of 
`Failed to renew Spotify Token` in replit containers.
Unlike the previous pull request i did, this uses replit.nix for faster performance.
This ocmmit is also a remake of #1024 by @ItzCuteAkemi

### CODE REVIEW

**Comment by JotaroKujo0525** [comment]
Screenshot_20220802-052153

This is the issue in replit devices in the current v5

Screenshot_20220802-052203

This has now been fixed

**Comment by ItzCuteAkemi** [comment]
Try change the language to Bash instead of Nix

**Comment by JotaroKujo0525** [comment]
i already did...

**Comment by DarrenOfficial** [comment]
go rebase commit

**Review by DarrenOfficial — APPROVED** [review]

**Pull request merged**
