### PR TITLE
fix: Error in invite link

### PR DESCRIPTION
**Pull request by DevAmiyo**
**Please describe the changes this PR makes and why it should be merged:**
This PR fixes the issue (#888) causing the invite.js to not replace all ',' in `invite.js`. A global .replace() should be used so that it replaces all `,` with `%20`

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by XstreamSpeed** [comment]
Bro the invite command link works just fine for me

**Comment by JotaroKujo0525** [comment]
It works fine for me too, do someone else encounter error?

**Comment by DarrenOfficial** [comment]
Invite works fine

**Comment by BioCla** [comment]
this fix is actually necessary. 
The current version works fine for bots which have only 2 scopes, but it would give the wrong link if you had any more than 2 scopes. 
This fix is optimal. Ty Amiyo

**Review by BioCla — APPROVED** [review]

**Comment by DarrenOfficial** [comment]
make sense

**Pull request merged**
