### PR TITLE
Fixes Server Mute

### PR DESCRIPTION
**Pull request by DananaBanana**
**Please describe the changes this PR makes and why it should be merged:**

When you server mute the bot it would stop working until the next song, now it's able to keep playing, and also automatically pauses.

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
Have you tested it?

**Comment by DananaBanana** [comment]
It's been running on my own version of the bot and it works

**Comment by Kakarot-0690** [comment]
yup it works

**Comment by DananaBanana** [comment]
Maybe it could be a good idea to make it announce that it automatically paused because of the mute?

**Comment by DarrenOfficial** [comment]
that would be great ig

**Pull request merged**
