### PR TITLE
Add thumbnail to save.js

### PR DESCRIPTION
**Pull request by XstreamSpeed**
**Please describe the changes this PR makes and why it should be merged:**
This adds a thumbnail to save.js to make the embed look better

**Before**
image

**After**
image

**Status and versioning classification:**
NodeJS: v16.7.0
OS: Linux
- Code changes have been tested against the Discord API

### CODE REVIEW

**Review by DarrenOfficial — CHANGES_REQUESTED** [review]
Format the code, the indexing is a bit off on this one

**Comment by DarrenOfficial** [comment]
use tabs not spaces

**Comment by XstreamSpeed** [comment]
> Format the code, the indexing is a bit off on this one

What do you mean, could you elaborate

**Comment by DarrenOfficial** [comment]
*Indentation (autocorrect), aka use tabs to make these lines the same.
234ED431-62DA-4E95-A025-B54908F3707A

**Comment by XstreamSpeed** [comment]
> *Indentation (autocorrect), aka use tabs to make these lines the same. 234ED431-62DA-4E95-A025-B54908F3707A

Alright thanks, will do

**Pull request closed without merging**
